from datetime import datetime
from app.extensions import db

class SyncRecord(db.Model):
    __tablename__ = 'sync_records'

    id = db.Column(db.Integer, primary_key=True)
    farm_id = db.Column(db.Integer, db.ForeignKey('farms.id', ondelete='CASCADE'), nullable=False, index=True)
    client_sync_id = db.Column(db.String(100), unique=True, nullable=False, index=True)  # UUID generated by Flutter client
    entity_type = db.Column(db.String(50), nullable=False)  # MILK, DELIVERY, EXPENSE, ANIMAL
    entity_id = db.Column(db.String(50), nullable=True)     # Backend ID once assigned
    action = db.Column(db.String(20), nullable=False)        # CREATE, UPDATE, DELETE
    status = db.Column(db.String(30), default='APPLIED', nullable=False)  # APPLIED, CONFLICT, REJECTED
    error_message = db.Column(db.String(255), nullable=True)
    synced_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    def to_dict(self):
        return {
            'id': self.id,
            'farm_id': self.farm_id,
            'client_sync_id': self.client_sync_id,
            'entity_type': self.entity_type,
            'entity_id': self.entity_id,
            'action': self.action,
            'status': self.status,
            'error_message': self.error_message,
            'synced_at': self.synced_at.isoformat() if self.synced_at else None
        }
